### ISSUE TITLE
About TCGA label

### ISSUE THREAD

**Issue by AlexNmSED** [HakimBenkirane/CustOmics#1]
Hello,  thank you for your work.

I would like to reproduce your method on our data. What is the classification label of TCGA? Can you provide it to me?

**Comment by HakimBenkirane** [comment]
Hi,

I appreciate your interest in our work.
The classification label used for TCGA is the tumor_type. This label combines the project_id specifying which cohort the sample is extracted from and the sample_type to account for normal samples. Normally both those information are pretty standard in the GDC Data Commons.

Thank you and I wish you the best
