### ISSUE TITLE
question about CustOmics

### ISSUE THREAD

**Issue by silvia1234567890** [HakimBenkirane/CustOmics#2]
Hello,

CustOmics looks like a very interesting tool, congratulations!
I was wondering if this tool can only be applied to cancer or also to other types of diseases? I have data of different types (transcriptomics, biomarkers,...) and I was looking for a way to integrate this data and make a machine learning model to correctly classify the patients... The disease is tuberculosis. Would it be possible to do something with CustOmics? 

Thank you in advance

**Comment by HakimBenkirane** [comment]
Hello,
Thank you for your interest in CustOmics. The model can in fact be used for other types of disease, there is no constraint on the end goal of the model. As long as you input the label to predict in the same way done in the example notebook it should be fine.

**Comment by silvia1234567890** [comment]
Perfect, thank you so much!

**Comment by silvia1234567890** [comment]
Perfect, thank you so much!
