### ISSUE TITLE
"Output 0 of BackwardHookFunctionBackward" on model.explain()

### ISSUE THREAD

**Issue by GhislainFievet** [HakimBenkirane/CustOmics#3]
Hello, nice work, I enjoyed the paper.

I am trying to run the example_notebook.ipynb notebook but I get the following error when I run the model.explain() lines:
```
RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.
```

I searched the internet for a solution and experimented with several approaches, but none were successful. Do you have any suggestions?

Thank you.
Ghislain

**Comment by HakimBenkirane** [comment]
Hi
Thank you for your interest in the paper.
This behaviour may be due to the version of the shap library, try and see if you downgrade it to 0.42.1. I’m actually trying to fix this issue but I think it’s linked to the shap version

Best
Hakim

**Comment by GhislainFievet** [comment]
Hi,

thank you, works perfectly.

Regards
Ghislain
